### ISSUE TITLE
Popup / Lightbox für Charts implementieren

### ISSUE THREAD

**Issue by Donskelle** [energiekollektiv/openmod.sh-id#9]

**Comment by Donskelle** [comment]
Added Demo:
http://176.28.8.110:8001/static/iD/lightbox/index.html

**Comment by Donskelle** [comment]
Springt im Chart

**Comment by cswh** [comment]
looks already good. so next step is the replacement of the menu popup links, e.g. http://176.28.8.110:8001/static/iD/timeseries/gettimeseries.html?id=n3&view=variable_costs
